"""
qclaw_configurator.py — Poor Man's Configurator (Karpathy style)

来源：karpathy/nanoGPT configurator.py
设计：exec() 直接在调用者命名空间覆盖变量，比JSON/YAML更Pythonic

用法：
    # 在脚本顶部：
    from qclaw_configurator import configure
    configure(globals())  # 加载默认配置
    configure(globals(), 'my_config.py')  # 从文件加载
    configure(globals(), {'batch_size': 32, 'model': 'gpt-4'})  # 字典覆盖
    configure(globals(), ['--batch_size=32', '--model=gpt-4'])  # 命令行风格
"""

import os
import sys
from ast import literal_eval
from pathlib import Path
from typing import Optional, Union


def configure(
    namespace: dict,
    source: Optional[Union[str, Path, dict, list]] = None,
    defaults: Optional[dict] = None,
):
    """
    在命名空间中设置配置，支持多种来源覆盖。
    
    优先级（低→高）：
    1. defaults 参数
    2. source 文件/字典/命令行参数
    3. 已存在的同名变量（最高优先级，不会被覆盖）
    
    Args:
        namespace: 目标命名空间（通常传 globals()）
        source: 配置来源，支持：
            - str/Path: Python文件路径，exec执行
            - dict: 直接合并
            - list: 命令行参数列表，如 ['--key=value']
        defaults: 默认配置字典
    """
    # 1. 设置默认值（最低优先级）
    if defaults:
        for key, val in defaults.items():
            if key not in namespace:
                namespace[key] = val
    
    # 2. 从source加载
    if source is None:
        # 尝试自动查找配置文件
        candidates = ['qclaw_config.py', 'config.py', '.qclaw_config.py']
        for c in candidates:
            if os.path.exists(c):
                source = c
                break
    
    if source is None:
        return
    
    if isinstance(source, (str, Path)):
        # 从Python文件加载（exec模式，Karpathy风格）
        path = str(source)
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as f:
                code = f.read()
            exec(code, namespace)
        else:
            raise FileNotFoundError(f"Config file not found: {path}")
    
    elif isinstance(source, dict):
        # 从字典加载
        for key, val in source.items():
            namespace[key] = val
    
    elif isinstance(source, (list, tuple)):
        # 从命令行参数列表加载（--key=value 格式）
        for arg in source:
            if isinstance(arg, str) and arg.startswith('--') and '=' in arg:
                key_val = arg[2:]  # 去掉 --
                key, val_str = key_val.split('=', 1)
                try:
                    val = literal_eval(val_str)
                except (ValueError, SyntaxError):
                    val = val_str  # 无法解析就当字符串
                namespace[key] = val
            elif isinstance(arg, str) and not arg.startswith('--'):
                # 可能是配置文件路径
                if os.path.exists(arg):
                    with open(arg, 'r', encoding='utf-8') as f:
                        exec(f.read(), namespace)


def save_config(namespace: dict, path: str, keys: Optional[list] = None):
    """
    保存当前配置到Python文件
    
    Args:
        namespace: 命名空间（通常传 globals()）
        path: 输出文件路径
        keys: 只保存这些key，None则保存所有非内置变量
    """
    import builtins
    builtin_names = set(dir(builtins))
    
    if keys:
        save_items = {k: namespace[k] for k in keys if k in namespace}
    else:
        save_items = {
            k: v for k, v in namespace.items()
            if not k.startswith('_') 
            and k not in builtin_names
            and isinstance(v, (int, float, str, bool, list, dict, tuple))
        }
    
    lines = ["# Auto-generated by qclaw_configurator.py\n"]
    for k, v in sorted(save_items.items()):
        lines.append(f"{k} = {repr(v)}\n")
    
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines)


if __name__ == "__main__":
    # 自测
    ns = {}
    configure(ns, defaults={'batch_size': 16, 'model': 'gpt-3.5', 'temperature': 0.7})
    print(f"Defaults: batch_size={ns['batch_size']}, model={ns['model']}")
    
    # 命令行覆盖
    configure(ns, ['--batch_size=32', '--model=gpt-4'])
    print(f"Override: batch_size={ns['batch_size']}, model={ns['model']}")
    
    # 字典覆盖
    configure(ns, {'temperature': 0.9})
    print(f"Dict: temperature={ns['temperature']}")
    
    print("OK")
